// import jsPDF from "jspdf";

// export const downloadPDF = () => {

//   const doc = new jsPDF();

//   doc.setFontSize(18);
//   doc.text("Pipeline Calculation Report", 20, 20);

//   doc.setFontSize(12);

//   doc.text("Project Name: Demo Project", 20, 40);
//   doc.text("Design Pressure: 10 bar", 20, 50);
//   doc.text("Temperature: 120 °C", 20, 60);

//   doc.text("Required Thickness: 12 mm", 20, 80);
//   doc.text("Actual Thickness: 14 mm", 20, 90);

//   // Download
//   doc.save("pipeline-report.pdf");
// };



import jsPDF from "jspdf";

export const downloadPDF = () => {

  const doc = new jsPDF();

  // TITLE
  doc.setFontSize(22);
  doc.setTextColor(40, 40, 40);
  doc.text("ASME PIPE REPORT", 20, 20);

  // LINE
  doc.line(20, 25, 190, 25);

  // SECTION
  doc.setFontSize(14);

  doc.text("Project Information", 20, 40);

  doc.setFontSize(11);

  doc.text("Project: Pipeline-X", 25, 50);
  doc.text("Pressure: 12 bar", 25, 58);
  doc.text("Temperature: 180 °C", 25, 66);

  doc.text("Required Thickness: 10.2 mm", 25, 80);
  doc.text("Actual Thickness: 12 mm", 25, 88);

  // FOOTER
  doc.setFontSize(10);
  doc.text("Generated by Pipeline Calculator", 20, 280);

  doc.save("ASME_Report.pdf");
};

